# This rule is not used by the project ollama-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ollama.sivchari.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ollama-operator
    app.kubernetes.io/managed-by: kustomize
  name: modelset-admin-role
rules:
- apiGroups:
  - ollama.sivchari.io
  resources:
  - modelsets
  verbs:
  - '*'
- apiGroups:
  - ollama.sivchari.io
  resources:
  - modelsets/status
  verbs:
  - get
