---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ollama.sivchari.io
  resources:
  - modelsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ollama.sivchari.io
  resources:
  - modelsets/finalizers
  verbs:
  - update
- apiGroups:
  - ollama.sivchari.io
  resources:
  - modelsets/status
  verbs:
  - get
  - patch
  - update
